apiVersion: "ingress.oraclecloud.com/v1beta1"
kind: IngressClassParameters
metadata:
  name: icp
spec:
  compartmentId: "ocid1.compartment.oc1..aaaaaaaanxm4oucgt5pkgd7sw2vouvckvvxan7ca2lirowaao7krnzlkdkhq"
  subnetId: "ocid1.subnet.oc1.ap-sydney-1.aaaaaaaalcdwang7o736t4xjxeitcuoogjhdibhbdf46ltsndqlrqx4bheaq"
  loadBalancerName: "oci-native-ingress-lb"
  isPrivate: false
  maxBandwidthMbps: 100
  minBandwidthMbps: 10
